name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
        env:
          USER: root

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ats-analyzer-apk
          path: ${{ steps.buildozer.outputs.filename }}
